CREATE TABLE communication_drafts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reminder_id BIGINT UNSIGNED NOT NULL,
    member_id BIGINT UNSIGNED NULL,
    channel VARCHAR(24) NOT NULL DEFAULT 'email',
    recipient_label VARCHAR(160) NOT NULL,
    subject VARCHAR(160) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    version INT UNSIGNED NOT NULL DEFAULT 1,
    provider VARCHAR(64) NOT NULL DEFAULT 'mock-email',
    created_by BIGINT UNSIGNED NOT NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    sent_by BIGINT UNSIGNED NULL,
    sent_at DATETIME NULL,
    send_idempotency_key VARCHAR(128) NULL,
    provider_message_id VARCHAR(128) NULL,
    provider_payload JSON NULL,
    last_error VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_communication_reminder (reminder_id),
    UNIQUE KEY uk_communication_send_idempotency (send_idempotency_key),
    UNIQUE KEY uk_communication_provider_message (provider, provider_message_id),
    CONSTRAINT fk_communication_reminder FOREIGN KEY (reminder_id) REFERENCES reminders(id),
    CONSTRAINT fk_communication_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
    CONSTRAINT fk_communication_creator FOREIGN KEY (created_by) REFERENCES staff_users(id),
    CONSTRAINT fk_communication_approver FOREIGN KEY (approved_by) REFERENCES staff_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_communication_sender FOREIGN KEY (sent_by) REFERENCES staff_users(id) ON DELETE SET NULL,
    INDEX idx_communication_status_updated (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
